[package]
name = "urlService"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "urlService"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.14.0"

[dev-dependencies]
marine-rs-sdk-test = "0.16.1"
